services:
  db:
    image: docker.io/library/postgres:16-alpine3.20
    container_name: transcribeflow-db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: docker.io/library/adminer:latest
    container_name: transcribeflow-adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db

  redis:
    image: redis:alpine
    container_name: transcribeflow-redis
    ports:
      - "6379:6379"
    restart: always

  ai-engine:
    build:
      context: ./ai-engine
      dockerfile: Dockerfile
    container_name: transcribeflow-ai
    restart: always
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - CUDA_VISIBLE_DEVICES=0

  backend-java:
    build:
      context: .
    container_name: transcribeflow-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}

      - AI_HOST=${AI_HOST}
      - AI_PORT=${AI_PORT}

      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_EXPIRATION_TIME=${JWT_EXPIRATION_TIME}
      - JWT_REFRESH_EXPIRATION_TIME=${JWT_REFRESH_EXPIRATION_TIME}
    depends_on:
      - db
      - ai-engine
      - redis

volumes:
  postgres_data: